# Generated by Django 6.0.4 on 2026-04-09 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_type', models.CharField(choices=[('text', 'Text Generator'), ('article', 'Article Writer'), ('resume', 'Resume Review'), ('image_generate', 'Image Generator'), ('image_edit', 'Image Editor (remove object/background)')], max_length=20)),
                ('prompt', models.TextField()),
                ('result_text', models.TextField(blank=True, null=True)),
                ('result_image_url', models.URLField(blank=True, null=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('cost_in_credits', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Generation',
                'verbose_name_plural': 'AI Generations',
                'ordering': ['-created_at'],
            },
        ),
    ]
